# Generated by Django 2.0 on 2018-03-25 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Название компании')),
                ('city', models.CharField(max_length=80, verbose_name='Город')),
            ],
        ),
    ]
