# Generated by Django 2.0 on 2018-03-25 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компании', 'verbose_name_plural': 'Компании'},
        ),
    ]
