# Generated by Django 2.0 on 2018-03-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0002_auto_20180325_1938'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Все компании', 'verbose_name_plural': 'Все компании'},
        ),
    ]
