# Generated by Django 2.0 on 2018-03-29 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0009_auto_20180329_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='annex/img/avatar_big.png', upload_to='annex/img', verbose_name='Аватар'),
        ),
    ]
