# Generated by Django 2.0 on 2018-03-29 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0011_auto_20180329_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='annex/img/avatar_big.png', null=True, upload_to='annex/img/%Y/%m/%d', verbose_name='Аватар'),
        ),
    ]
