# Generated by Django 2.0 on 2018-03-29 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0012_auto_20180329_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='background',
            field=models.ImageField(blank=True, default='', null=True, upload_to='annex/img/%Y/%m/%d', verbose_name='Фон'),
        ),
    ]
