# Generated by Django 2.0 on 2018-03-29 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annex', '0013_company_background'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='background',
            field=models.ImageField(default='', upload_to='annex/img/%Y/%m/%d', verbose_name='Фон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='annex/img/avatar_big.png', null=True, upload_to='annex/img/%Y/%m/%d', verbose_name='Аватар'),
        ),
    ]
